spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wuyi_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: wuyi-mall

  jpa:
    hibernate:
      ddl-auto: update   # 开发阶段可以用 update
    show-sql: true  
  
  # 配置Jackson，使用驼峰命名
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

# 文件上传路径配置
file:
  upload:
    path: d:/Java_program/wuyi_mall/uploads/

server:
  port: 8081
  
  # 静态资源访问配置
  web:
    resources:
      static-locations: classpath:/static/,file:${file.upload.path}
